In [48]:
#! /usr/bin/python
from pprint import pprint
from collections import defaultdict

import datetime
import sys
import json
import mysql.connector
import os


d=defaultdict(list)
user=[]
user_list=[]

print ("Aruna python 1st program")
cnx = mysql.connector.connect(user='root', password= 'root', host = 'localhost',database = 'twitterSchema')

with open('/media/data/sensemaking/dataset/centralpartiet/clean/fix_out_AprilTweets.dat') as f:
    content = f.readlines()
# you may also want to remove whitespace characters like `\n` at the end of each line
content = [x.strip("/n") for x in content] 
for x in content:
    jsondata = json.loads(x)
    tweet_id= jsondata['id']
    text= jsondata['text']
    retweet_count=jsondata['retweet_count']
    in_reply_to_user_id= jsondata['in_reply_to_user_id_str']
    in_reply_to_status_id= jsondata['in_reply_to_status_id_str']
    # user table data
    userdata= jsondata['user']
    id_str=  int(userdata['id_str'])
    if userdata['verified']:
        verified=1
        
    else:
        verified=0
    followers_count= userdata['followers_count']
    id=userdata['id']
    description= (userdata['description']).encode('utf-8','ignore')
    friends_count=userdata['friends_count']
    location=userdata['location'].encode('utf-8','ignore')
    created_at_date= datetime.datetime.strptime(userdata['created_at'], "%a %b %d %H:%M:%S +0000 %Y")
    date= (created_at_date).date()
    time= (created_at_date).time()
    created_at= datetime.datetime.combine(date,time)
    name=(userdata['name']).encode('utf-8','ignore')
    user.append((id_str,[verified,followers_count,id,description, friends_count, location, created_at,name]))

  
#to eliminate duplicate entrys in "user" list 
user_noduplicate =dict(user)

# to convert  [k,[v]]  into  a  list [k,v]

for k,v in user_noduplicate.items():
    user_list.append(tuple([k]+v))

#for x in user_list]
print(len(user_list))
#print(user_list)
cursor = cnx.cursor(prepared=True)

 #add_tweet= "INSERT INTO tweet(tweet_id, text, id_str, retweet_count, created_at, in_reply_to_user_id, in_reply_to_status_id) VALUES (%d, %r, %d, %d,'%s',?, ?)" % \
#                           (tweet_id, text, id_str, retweet_count, created_at, in_reply_to_user_id, in_reply_to_status_id)

# add_user= "INSERT INTO users(id_str,verified, followers_count, id, description,friends_count, location, created_at, name) VALUES (%d, %d, %d, %d, %r, %d , %r,  '%s', %r)" % (id_str,verified, followers_count, id, description,friends_count, location, created_at, name)


add_user= "INSERT INTO users(id_str,verified, followers_count, id, description,friends_count, location,created_at, name) VALUES (?, ?, ?, ?, ?, ? , ?, ?, ?)"
                            
#try:
cursor.executemany(add_user,user_list)
cnx.commit()
#except:
 #cnx.rollback()

cursor.close()
cnx.close()
f.close()

Aruna python 1st program
2998

IntegrityError: 1062 (23000): Duplicate entry '241950756' for key 'PRIMARY'

In [2]:
#! /usr/bin/python

# ::::::::::::::::::::It is working :::::::::::::::::::::
from pprint import pprint
from collections import defaultdict

import datetime
import sys
import json
import mysql.connector
import os
import pandas as pd

d=defaultdict(list)
user=[]
user_list=[]
path= '/media/data/sensemaking/dataset/centralpartiet/clean'
filename=[]

print ("Aruna python 1st program")
cnx = mysql.connector.connect(user='root', password= 'root', host = 'localhost',database = 'twitterSchema')

for file in os.listdir(path):
    filename= path+'/'+file 
    with open(filename) as f:
        content = f.readlines()
     # you may also want to remove whitespace characters like `\n` at the end of each line
    content = [x.strip("/n") for x in content] 
    for x in content:   
        try:
            if x.strip().endswith('}'):
       
               jsondata = json.loads(x,encoding='latin1')
        except ValueError as ex:
            print(x)
            raise ValueError(ex)

        tweet_id= jsondata['id']

        text= jsondata['text']

        retweet_count=jsondata['retweet_count']

        in_reply_to_user_id= jsondata['in_reply_to_user_id_str']
        in_reply_to_status_id= jsondata['in_reply_to_status_id_str']

    # user table data

        userdata= jsondata['user']
        id_str=  int(userdata['id_str'])
        if userdata['verified']:
            verified=1
        else:
            verified=0              
        followers_count= userdata['followers_count']
        id=userdata['id']
        description= (userdata['description']).encode('utf-8','ignore')
        friends_count=userdata['friends_count']
        location=userdata['location'].encode('utf-8','ignore')
        created_at_date= datetime.datetime.strptime(userdata['created_at'], "%a %b %d %H:%M:%S +0000 %Y")
        date= (created_at_date).date()
        time= (created_at_date).time()
        created_at= datetime.datetime.combine(date,time)
        name=(userdata['name']).encode('utf-8','ignore')
        user.append((id_str,[verified,followers_count,id,description, friends_count, location, created_at,name]))
    print(len(user))

# to eliminate duplicate entrys in "user" list 
user_noduplicate =dict(user)

# to convert  [k,[v]]  into  a  list [k,v]

for k,v in user_noduplicate.items():
    user_list.append(tuple([k]+v))

#for x in user_list]
print(len(user_list))
#print(user_list)
cursor = cnx.cursor(prepared=True)

 #add_tweet= "INSERT INTO tweet(tweet_id, text, id_str, retweet_count, created_at, in_reply_to_user_id, in_reply_to_status_id) VALUES (%d, %r, %d, %d,'%s',?, ?)" % \
#                           (tweet_id, text, id_str, retweet_count, created_at, in_reply_to_user_id, in_reply_to_status_id)

# add_user= "INSERT INTO users(id_str,verified, followers_count, id, description,friends_count, location, created_at, name) VALUES (%d, %d, %d, %d, %r, %d , %r,  '%s', %r)" % (id_str,verified, followers_count, id, description,friends_count, location, created_at, name)


add_user= "INSERT INTO users(id_str,verified, followers_count, id, description,friends_count, location,created_at, name) VALUES (?, ?, ?, ?, ?, ? , ?, ?, ?)"
                            
#try:
cursor.executemany(add_user,user_list)
cnx.commit()
#except:
 #cnx.rollback()

cursor.close()
cnx.close()

Aruna python 1st program
2632
9401
18698
22680
25784
32826
35189
45947
50513
55372
57502
61605
64303
71603
80117
80799
85148
87288
15163

In [1]:
#! /usr/bin/python

# ::::::::::::::::::::It is working :::::::::::::::::::::
from pprint import pprint
from collections import defaultdict

import datetime
import sys
import json
import mysql.connector
import os
import pandas as pd

d=defaultdict(list)
user=[]
user_list=[]
filename=[]
filelist=[]

path= '/media/data/sensemaking/dataset'

print ("Aruna python 1st program")

cnx = mysql.connector.connect(user='root', password= 'root', host = 'localhost',database = 'twitterSchema')

for filedir in os.listdir(path):
    filelist.append(path+'/'+file+'/clean') 
    for file in os.listdir(path):
        filename= path+'/'+file 
        with open(filename) as f:
            content = f.readlines()
         # you may also want to remove whitespace characters like `\n` at the end of each line
        content = [x.strip("/n") for x in content] 
        for x in content:   
            try:
                if x.strip().endswith('}'):
                    jsondata = json.loads(x,encoding='latin1')
            except ValueError as ex:
                #print(x)
                raise ValueError(ex)

            tweet_id= jsondata['id']

            text= jsondata['text']

            retweet_count=jsondata['retweet_count']

            in_reply_to_user_id= jsondata['in_reply_to_user_id_str']
            in_reply_to_status_id= jsondata['in_reply_to_status_id_str']

        # user table data

            userdata= jsondata['user']
            id_str=  int(userdata['id_str'])
            if userdata['verified']:
                verified=1
            else:
                verified=0              
            followers_count= userdata['followers_count']
            id=userdata['id']
            description= (userdata['description']).encode('utf-8','ignore')
            friends_count=userdata['friends_count']
            location=userdata['location'].encode('utf-8','ignore')
            created_at_date= datetime.datetime.strptime(userdata['created_at'], "%a %b %d %H:%M:%S +0000 %Y")
            date= (created_at_date).date()
            time= (created_at_date).time()
            created_at= datetime.datetime.combine(date,time)
            name=(userdata['name']).encode('utf-8','ignore')
            user.append((id_str,[verified,followers_count,id,description, friends_count, location, created_at,name]))
        print(len(user))

# to eliminate duplicate entrys in "user" list 
user_noduplicate =dict(user)

# to convert  [k,[v]]  into  a  list [k,v]

for k,v in user_noduplicate.items():
 user_list.append(tuple([k]+v))

#for x in user_list]
print(len(user_list))
#print(user_list)
cursor = cnx.cursor(prepared=True)

 #add_tweet= "INSERT INTO tweet(tweet_id, text, id_str, retweet_count, created_at, in_reply_to_user_id, in_reply_to_status_id) VALUES (%d, %r, %d, %d,'%s',?, ?)" % \
#                           (tweet_id, text, id_str, retweet_count, created_at, in_reply_to_user_id, in_reply_to_status_id)

# add_user= "INSERT INTO users(id_str,verified, followers_count, id, description,friends_count, location, created_at, name) VALUES (%d, %d, %d, %d, %r, %d , %r,  '%s', %r)" % (id_str,verified, followers_count, id, description,friends_count, location, created_at, name)


add_user= "INSERT INTO users(id_str,verified, followers_count, id, description,friends_count, location,created_at, name) VALUES (?, ?, ?, ?, ?, ? , ?, ?, ?)"
                            
#try:
cursor.executemany(add_user,user_list)
cnx.commit()
#except:
 #cnx.rollback()

cursor.close()
cnx.close()

Aruna python 1st program

NameError: name 'file' is not defined